/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestTransformer;

import org.junit.Test;
import static org.junit.Assert.*;
import subject.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App t = new App();
        assertEquals(t.getVal(), 189+29+100+105);
    }

    @Test
    public void test_transformer() throws Exception {
        new App().transform();
    }
}
