/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestTransformer;

import subject.*;
import worker.*;

public class App {

    public int getVal() {
        Storage.reset();
        StaticSubject.noRefun();
        NonStaticSubject nss = NonStaticSubject.create(1298, 9l);
        nss.noReturn();
        return StaticSubject.getRefun() + nss.val() + Storage.feed + Storage.foo + nss.lift(80);
    }

    public static void main(String[] args) throws Exception {
        new CompilationUnitWorker().transform("./src/test/java/TestTransformer/MockTest.java");
    }
}
